version: "3.8"

services:
# mariadb
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./srcs/requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - ./srcs/.env
    networks:
      - inception
    restart: always
# nginx
  nginx:
    image: nginx
    container_name: nginx
    build: ./srcs/requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
# wordpress
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./srcs/requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - ./srcs/.env
    networks:
      - inception
    restart: always
# volumes
volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /~/inception/volumes/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /~/inception/volumes/wordpress
      o: bind
      type: none
#network
networks:
  inception:
    name: inception