version: "3.8"

# volumes
volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/jeshin/inception/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/jeshin/inception/data/wordpress
      o: bind
      type: none
services:
# mariadb
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - inception
    restart: always
# nginx
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - ./.env
    networks:
      - inception
    restart: always
# wordpress
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
      - redis
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - ./.env
    networks:
      - inception
    restart: always
# redis
  redis:
    image: redis
    container_name: redis
    build: ./requirements/bonus/redis
    env_file:
      - ./.env
    networks:
      - inception
    restart: always
# vsftpd
  vsftpd:
    image: vsftpd
    container_name: vsftpd
    build: ./requirements/bonus/vsftpd
    env_file:
      - ./.env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "21:21"
      - "4559:4559"
    restart: always
#network
networks:
  inception:
    name: inception